#!/usr/bin/env python
import sys
from optparse import OptionParser
from wares.spectrometer.spectrometer_socket import SpectrometerSocketServer
from wares.logging import logger
import daemon
from daemon import pidfile

logger.name = __name__

def start_spectrometer(options):
    spec_sock = SpectrometerSocketServer(HOST=options.hostname,
                                     PORT=options.portnumber,
                                     roach_id=options.roachid,
                                     katcp_port=options.katcp_port)
    #print "Waiting for socket connection from client"
    logger.info("Spectrometer Socket server started")
    logger.info("Waiting for socket connection from client")
    spec_sock.listen(10)
    while True:
        spec_sock.accept()
        while True:
            if spec_sock.process_spectrometer_command():
                #print "Processed command"
                logger.info("Processed command")
                #print "Ctrl-C to quit"
                logger.info( "Ctrl-C to quit")
            else:
                spec_sock.conn_close()
                break
                                     
# def start_daemon(options):
#     print "Starting Daemon"
#     with daemon.DaemonContext(
#             pidfile=pidfile.TimeoutPIDLockFile(options.pidfile),
#     ) as context:
#         start_spectometer(options)



if __name__ == '__main__':
    usage = "usage: %prog [options]"
    parser = OptionParser(usage=usage)
    parser.add_option("-H", "--hostname", dest="hostname",
                      action="store", default="localhost",
                      help="Hostname for server (default %default)")
    parser.add_option("-p", "--port", dest="portnumber",
                      action="store", type="int",
                      default=9990,
                      help="Port for spec server to bind on (default %default)")
    parser.add_option("-r", "--roach", dest="roachid",
                      action="store", type="int",
                      default=0,
                      help="Roach ID (can be one of 0 to 3: default %default)")
    parser.add_option("-k", "--katcp", dest="katcp_port",
                      action="store", type="int",
                      default=7147,
                      help="KATCP Port on ROACH board (default %default)")
    parser.add_option('-P', '--pid-file', dest="pidfile", 
                      action="store", default='/var/run/spec_daemon.pid',
                      help="pid file location (default %default)")
    (options, args) = parser.parse_args()
    start_spectrometer(options)
    
